workspace:
  base: /go
  path: src/github.com/dysonfrost/kubernetes

pipeline:

  service:
    image: webdevops/ansible:latest
    commands:
      - mkdir /root/.ssh && echo "$$SSH_KEY" > ~/.ssh/ansible_id_rsa && chmod 0600 ~/.ssh/ansible_id_rsa
      - ansible -m ping prod -i ansible/inventory
      - ansible-playbook -i ansible/inventory -l prod ansible/playbook.yml --syntax-check

    secrets: [SSH_KEY]


# ON EST BON FAUT SAVOIR UTILISER SSH-COPY-ID MAINTENANT