workspace:
  base: /go
  path: src/github.com/dysonfrost/kubernetes

pipeline:

  run:
    image: webdevops/ansible:latest
    commands:
      - mkdir /root/.ssh && echo "$$SSH_KEY" > ~/.ssh/ansible_id_rsa && chmod 0600 ~/.ssh/ansible_id_rsa
      - ansible -m ping prod -i ansible/inventory
      - ansible-playbook -i ansible/inventory -l prod ansible/playbook.yml --syntax-check
      - ansible-playbook -i ansible/inventory -l prod ansible/playbook.yml
    secrets: [SSH_KEY]

  notify:
    image: drillster/drone-email
    from: noreply@github.com
    host: smtp.mailgun.org
    username: $$email_username
    password: $$email_password
    recipients: $$email_recipients
    secrets: [ email_username, email_password, email_recipients ]
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ build.branch }} - {{ truncate build.commit 8 }})
    body: >
      You had one job phil.

branches: master


  # notify:
  #   image: drillster/drone-email
  #   host: $$SMTP_HOST
  #   username: $$MAIL_USERNAME
  #   password: $$MAIL_SECRET
  #   from: $$DRONE_DOMAIN
  #   recipients: [ $$MAIL_RECIPIENT ]
  #   secrets: [SMTP_HOST, MAIL_USERNAME, MAIL_SECRETDRONE_DOMAIN, MAIL_RECIPENT]