workspace:
  base: /go
  path: src/github.com/dysonfrost/kubernetes

pipeline:

  service:
    image: webdevops/ansible:latest
    commands:
      - echo "helloworld" > ~/hello
      - mkdir /root/.ssh && echo $$SSH_KEY > /root/.ssh/drone_id_rsa && chmod 0600 /root/.ssh/drone_id_rsa
      - echo $$SSH_CONFIG > ansible/ssh_manager.cfg
      - cat ansible/ssh_manager.cfg
      - ansible -m ping prod -i ansible/inventory
    secrets: [SSH_KEY, SSH_CONFIG]

# ON EST BON FAUT SAVOIR UTILISER SSH-COPY-ID MAINTENANT