workspace:
  base: /go
  path: src/github.com/dysonfrost/kubernetes

pipeline:

  run:
    image: webdevops/ansible:latest
    commands:
      - mkdir /root/.ssh && echo "$$SSH_KEY" > ~/.ssh/ansible_id_rsa && chmod 0600 ~/.ssh/ansible_id_rsa
      - ansible -m ping prod -i ansible/inventory
      - ansible-playbook -i ansible/inventory -l prod ansible/playbook.yml --syntax-check
      - ansible-playbook -i ansible/inventory -l prod ansible/playbook.yml
    secrets: [SSH_KEY]

  slack:
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: zuckerbot
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}


  # notify:
  #   image: drillster/drone-email
  #   host: $$SMTP_HOST
  #   username: $$MAIL_USERNAME
  #   password: $$MAIL_SECRET
  #   from: $$DRONE_DOMAIN
  #   recipients: [ $$MAIL_RECIPIENT ]
  #   secrets: [SMTP_HOST, MAIL_USERNAME, MAIL_SECRETDRONE_DOMAIN, MAIL_RECIPENT]