---
# tasks file for verify-goss
- name: Waiting for containers to start
  wait_for: timeout=10
  delegate_to: localhost

- name: Check that Goss exists
  stat:
    path: "{{ goss_bin }}"
  register: stat_result

- name: Install Goss
  file:
    shell: |
      curl -fsSL https://goss.rocks/install | sudo sh
  when: stat_result.stat.exists == False

- template:
    dest: "{{ goss_path }}"
    src: "{{ goss_tpl_name }}"

- name: Goss valide
  command: |
    goss validate {{ goss_path }}
  register: goss

- name: Goss results
  debug: 
    var: "{{ goss.stdout_lines | to_json }}"

- name: Cleaning artifacts
  file:
    state: absent
    path: "{{ goss_path }}"
