kind: PersistentVolume
apiVersion: v1
metadata:
  name: drone-pv-1
  labels:
    type: local
    app: drone
spec:
  storageClassName: drone
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/drone"

