apiVersion: v1
kind: Pod
metadata:
  name: drone-oauth
  namespace: drone
spec:
  containers:
  - name: drone
    image: drone/drone:1.0.0
    env:
    - name: DRONE_KUBERNETES_ENABLED
      value: "true"
    - name: DRONE_KUBERNETES_NAMESPACE
      value: drone
    - name: DRONE_GITHUB_SERVER
      value: https://github.com
    - name: DRONE_GITHUB_CLIENT_ID
      value: # Github client id
    - name: DRONE_GITHUB_CLIENT_SECRET
      value: # Github client secret 
    - name: DRONE_RPC_SECRET
      value: # RPC secret ($ openssl rand -hex 16)
    - name: DRONE_SERVER_HOST
      value: # drone.domain
    - name: DRONE_SERVER_PROTO
      value: # http or https
    ports:
      - containerPort: 80
      - containerPort: 443
 
