---
# tasks file for deploy-droppy
- name: Install droppy
  command: "kubectl apply -f -"
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'Namespace.yaml.j2') }}"
    - "{{ lookup('template', 'Volumes.yaml.j2') }}"
    - "{{ lookup('template', 'VolumeClaims.yaml.j2') }}"
    - "{{ lookup('template', 'Deployment.yaml.j2') }}"
    - "{{ lookup('template', 'Service.yaml.j2') }}"
    - "{{ lookup('template', 'Ingress.yaml.j2') }}"

- name: Waiting for container to start
  wait_for: timeout=10
  delegate_to: localhost

- name: Register External IP Address allocated to droppy
  shell: |
    kubectl -n {{ k8s_droppy_namespace }} get service {{ k8s_droppy_service }} -o jsonpath='{..ip}'
  register: external_ip

- set_fact:
    k8s_droppy_externalIP: "{{ external_ip.stdout }}"
# vim: set ts=2 sw=2:
