kind: PersistentVolume
apiVersion: v1
metadata:
  name: droppy-pv-1
  labels:
    type: local
    app: droppy
spec:
  storageClassName: droppy-config
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/droppy/config"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: droppy-pv-2
  labels:
    type: local
    app: droppy
spec:
  storageClassName: droppy-files
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/droppy/files"

